---
name: Continuous Deployment

on: push

jobs: 
  hello-gh-actions:
    name: Hello Github Actions
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Tests 
        run: echo "RUNNING TESTS!"