---
name: Continuous Deployment

on: push

jobs: 
  test:
    name: test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
  
  lint:
    name: My-Lint
    runs-on: ubuntu-18.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: My-Lint
        run: docker-compose run --rm app sh -c "python manage.py flake8"